# Generated by Django 4.0.6 on 2022-08-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iems_api.department')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['status_name'],
            },
        ),
        migrations.CreateModel(
            name='Enchroachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enchrt_id', models.CharField(max_length=20, null=True, unique=True)),
                ('enchrt_type', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('subregion', models.CharField(max_length=20)),
                ('encrt_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dist_from_center_of_asset', models.IntegerField()),
                ('criticality', models.CharField(max_length=6, null=True)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iems_api.department')),
                ('status_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iems_api.status')),
            ],
            options={
                'verbose_name': 'Enchroachment',
                'verbose_name_plural': 'Enchroachments',
                'ordering': ['enchrt_id'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name'], name='iems_api_de_departm_6cffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status_name'], name='iems_api_st_status__ad4b27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('department_name', 'status_name')},
        ),
        migrations.AddIndex(
            model_name='enchroachment',
            index=models.Index(fields=['enchrt_id'], name='iems_api_en_enchrt__edb255_idx'),
        ),
    ]
