# Generated by Django 4.0.6 on 2022-08-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iems_api', '0003_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enchroachment',
            options={'verbose_name': 'Enchroachment', 'verbose_name_plural': 'Enchroachments'},
        ),
        migrations.RemoveIndex(
            model_name='enchroachment',
            name='iems_api_en_enchrt__edb255_idx',
        ),
    ]
