# Generated by Django 4.0.6 on 2022-08-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iems_api', '0004_alter_enchroachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={},
        ),
    ]
