# Generated by Django 3.2 on 2022-08-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iems_api', '0005_alter_status_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enchroachment',
            options={'ordering': ['enchrt_id'], 'verbose_name': 'Enchroachment', 'verbose_name_plural': 'Enchroachments'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status_name'], 'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='enchroachment',
            name='enchrt_id',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enchroachment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='enchroachment',
            index=models.Index(fields=['enchrt_id'], name='iems_api_en_enchrt__edb255_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status_name'], name='iems_api_st_status__ad4b27_idx'),
        ),
    ]
